### ISSUE TITLE
Offline staff does not appear

### ISSUE THREAD

**Issue by fellow25** [RLNT/sinus-staff-list#2]
Offline staff does not appear

![Sem Título](https://user-images.githubusercontent.com/62182525/82671371-a34b2780-9c36-11ea-8fba-3508eeb895b3.png)

I tried to use the ID of the members offline and still not.

**Comment by DAmNRelentless** [comment]
All users that you want to appear in the list, have to connect at least once so the script is able to store their uid and their nickname.
