### ISSUE TITLE
Formatting is ignored

### ISSUE THREAD

**Issue by TheChaosToast** [RLNT/sinus-staff-list#27]
Hello everybody

I am currently testing the new version (1.8.0) of the Staff List Script. What struck me is that the formatting for the server groups is not taken into account when entering free text. If I have an empty group and enter free text there, the options in the "Group Section" are ignored. (Text is left justified and not underlined, instead of centered and underlined)

Pic1: Enter format and will also be displayed correctly in the groups
Pic2: The settings for the admin (empty group) are ignored
![Pic_1](https://user-images.githubusercontent.com/36563709/89164913-067f0180-d578-11ea-9c58-221b65adecbb.png)
![Pic_2](https://user-images.githubusercontent.com/36563709/89164915-07179800-d578-11ea-9553-5cf9d3166434.png)

**Comment by DAmNRelentless** [comment]
You can just use your own formatting for the empty group text.
This option is not related to whether you are using a custom template or not. It is a standalone option which can be formatted separately.

**Comment by DAmNRelentless** [comment]
@TheChaosToast What's the exact issue? Is this solved?
I am working on a new version and would like to have this solved before releasing it.
Would appreciate some more input.

**Comment by TheChaosToast** [comment]
Hello and good evening,

it is not really solved - for me;)

I find it difficult to format the freely definable text for empty groups if this is an already existing feature. it would be enough for me if the freely definable text was treated like a normal server group.

greetings

**Comment by DAmNRelentless** [comment]
The script aims to be as customizable as possible so the text for empty groups is also freely definable.
But I get your point with the group name so I decided to not automatically add the group name on empty groups and make it a placeholder instead.

**Comment by TheChaosToast** [comment]
That sounds like a good idea. How can I imagine that? That I can then freely define the group name myself? Isn't that the case now? Or am I confusing something?

**Comment by DAmNRelentless** [comment]
You don't have to redefine the group name.
If you want to use the group name in a section with an empty group, you can place the placeholder `%group%` instead and that will be replaced with the group's name in the actual message.
Like always this will use the default group name or the name you set in the group settings.

**Comment by TheChaosToast** [comment]
Very nice :)
