### ISSUE TITLE
Inaktive Status

### ISSUE THREAD

**Issue by xju2391x** [RLNT/sinus-staff-list#28]
Könntest ihr evtl. für den nächsten release von der Staff list noch einbauen wenn ein oder mehrere Teammitglied ca. 7 Tage  (nur Beispiel) nicht online waren das Sie als inaktive als Status eingetragen werden?

**Comment by DAmNRelentless** [comment]
Thanks for reaching out to us.

Sadly you decided to remove the whole issue template and also didn't use English which is  a requirement.
As stated in the template, issues without the required information or another language will be closed without any comment.

We try to keep this repository fair and everyone should be allowed/able to read it (same goes for issues and pull requests).
Furthermore, providing all the necessary information is essential for us to fix bugs and work on new features.
