### ISSUE TITLE
Inaktive Satus

### ISSUE THREAD

**Issue by xju2391x** [RLNT/sinus-staff-list#29]
Hi DAmNRelentless, could you insert at the next release that if a team member was about 7 Days (example only) were not entered on the TeamSpeak Server as Status Inactive?

**Comment by DAmNRelentless** [comment]
Thanks for reaching out to us.

Sadly you decided to remove the whole issue template which is a requirement.
As stated in the template, issues without the required information will be closed without any comment.

We try to keep this repository fair and everyone should be allowed/able to read it (same goes for issues and pull requests).
Furthermore, providing all the necessary information is essential for us to fix bugs and work on new features.
