### ISSUE TITLE
Users are not removed from list if group is removed

### ISSUE THREAD

**Issue by VeLutI0n** [RLNT/sinus-staff-list#3]
Wenn man jemandem die Team Gruppe wieder entzieht, dann steht er immernoch im Channel drinnen

**Comment by Jnnklxndr** [comment]
Ich habe genau das selbe Problem. Ich habe schon selbst versucht das Problem zu lösen, habe es aber leid ernicht hinbekommen :c

**Comment by VeLutI0n** [comment]
Ich habe mit dem Entwickler schon geschrieben. Er hat das ganze vergessen und wird das ganze Anfang nächster Woche fixen.

**Comment by Jnnklxndr** [comment]
Das hört sich schon einmal sehr gut an ich hatte auch schon versucht mich mit ihm in Verbindung zu setzen

**Comment by DAmNRelentless** [comment]
Derzeit reagiert das Script nur, wenn Nutzer auf den Server verbinden oder den Server verlassen (dazu zählen auch Kicks, Banns, Timeouts).

Ich werde noch ein Listener einfügen, damit die Beschreibung aktualisiert wird, sobald jemand aus einer der Gruppen entfernt wird. Das sollte das Problem lösen.

**Comment by VeLutI0n** [comment]
Ich finde dein Script echt mega gut. Vorallem dass alles automatisch geht und man nichts eintragen muss finde ich extrem gut.

**Comment by VeLutI0n** [comment]
Hast du rausgenommen, dass im Channel die User mit ID anzeigt werden. Also das man sie anklicken kann kann und Nachrichten schreiben kannst?

**Comment by DAmNRelentless** [comment]
Nein, das funktioniert noch ganz normal.

**Comment by VeLutI0n** [comment]
Bei mir werden die Namen nur noch normal angezeigt

**Comment by DAmNRelentless** [comment]
Support gibt es im Discord: https://discordapp.com/invite/Q3qxws6
