### ISSUE TITLE
Info Bar on Top

### ISSUE THREAD

**Issue by TheChaosToast** [RLNT/sinus-staff-list#37]
Hello everybody,

I have another suggestion for your great script. Thanks for that :)

I would like to insert a completely freely definable text in the upper area. This should be freely formattable and should have nothing to do with the existing formatting. So basically independent :)

The background is that I would like to add a kind of info bar at the top. The problem is, if I insert this now and something changes (Admin sets status to AWAY) then it's gone again.

I hope you know what I mean

best regards

TCT

**Comment by DAmNRelentless** [comment]
Do you want to have additional config fields in the config for a header and a footer so above and underneath the list?
I think there is no other way. When writing this script, I initially tried that it would only update itself and not what's already written in the channel description but that was too hard to keep track of.
I understand the reason of this feature request and this would be pretty easy, just tell me how you would like it.
Probably toggle-able options with multline text fields for header and footer.

**Comment by TheChaosToast** [comment]
Hello everybody,

the simplest would actually only be in the header. However, I am now only speaking for our server. But I don't think it's a problem if you can hide unnecessary lines.

I am happy that you implement this :)

best regards

**Comment by DAmNRelentless** [comment]
Added in https://github.com/RLNT/sinus-staff-list/commit/a75076979f090d2ce386e3842e487794512b00b1
