### ISSUE TITLE
Ein User in mehreren Gruppen nicht möglich

### ISSUE THREAD

**Issue by TheChaosToast** [RLNT/sinus-staff-list#7]
Servus, 

ein schönes Script mit einem kleinen Problem: Ich bin Inhaber von mehreren Gruppen. Admin Gruppe, Entwickler Gruppe und diversen anderen kleineren Gruppen.

Wenn ich die Entwickler Gruppe rausnehme, bin ich ganz normal in der Admin Gruppe zu sehen. Tu ich jetzt noch die Entwickler Gruppe hinzufügen, bin ich in der Admin Gruppe nicht mehr zu sehen und nur in der Entwicklergruppe sichtbar. Habe sämtlich einstellungen überprüft aber nix gefunden.

Wenn ich User zu einer Gruppe hinzufüge die auch Staff Stats anzeigen soll, müssen die User sich einmalig verbinden um sichtbar zu sein? Nur ne Frage weil mir das aufgefallen ist.  

Liebe Grüße

**Comment by DAmNRelentless** [comment]
Thanks for reaching out to us.
Sadly you decided to remove the whole issue template. As stated in the template, issues without the required information will be closed without any comment.
